# Generated by Django 5.0.1 on 2026-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
