# Generated by Django 5.0.1 on 2026-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_pdf_url_note_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pdf',
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
